### PR TITLE
update main.c

### PR DESCRIPTION
**Pull request by drax999**

### CODE REVIEW

**Comment by pwithnall** [comment]
Sorry, what’s the purpose of this change? `argc` is the conventional name for the number of arguments in the `argv` array.

**Comment by drax999** [comment]
sorry for that I was doing this just to complete my target for a free
t-shirt.

**Comment by pwithnall** [comment]
For what project/assignment?

**Comment by drax999** [comment]
for hacktober

**Comment by pwithnall** [comment]
I kindly suggest that you re-read the [values behind Hacktoberfest](https://hacktoberfest.digitalocean.com/details) and take a bit more time over your contributions. A submission which doesn’t improve the code or functionality, purely to get yourself a t-shirt, is a complete waste of my time and the Hacktoberfest resources. Please don’t do that.

That aside, I am happy to review, mentor and accept good faith contributions from people if there’s a problem they want to tackle.

**Pull request closed without merging**
